//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("FlyingGentleman")]
[assembly: AssemblyVersion("0.2.0.0")]
[assembly: AssemblyInformationalVersion("0.2.0.0")]
[assembly: AssemblyCompany("BSD Licensed")]
[assembly: AssemblyCopyright("BSD")]
[assembly: ComVisible(false)]