using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FlyingGentleman.Library
{
	/// <summary>
	/// A collection of events generated by the deployment.
	/// </summary>
	public class LogEventCollection : List<LogEvent>
	{
		/// <summary>
		/// Adds a log event to the collection.
		/// </summary>
		/// <param name="category">The category of the action which is creating the log event.</param>
		/// <param name="action">The name of the action which is creating the log event.</param>
		/// <param name="message">The content of the event.</param>
		public void Add(string category, string action, string message)
		{
			this.Add(new LogEvent(category, action, message));
		}
	}
}
